Write and read from wishbone via UART (new implementation)
lnls-dig/afc-gw pull request #7
Opened 2024-04-25 17:29 UTC by augustofg

The `xwb_rs232_syscon` core is not tailored to be controlled via software (it expects an VT100 compatible terminal and direct user interaction) and seems to have some bug that leads to random hangs. I've replaced it with a much simpler implementation that works reliably.

2024-04-25 20:10 UTC, guilhermerc requested changes

2024-04-25 20:10 UTC, guilhermerc commented on hdl/top/afc_v3/vivado/full/afc_full.vhd
> +      g_BENCH_MODE                             => false,
For consistency, please explicitly configure `g_UART_MASTER_BAUD` here. The same goes for the other top-level examples in hdl/top/afc_v3/vivado folder.

2024-05-02 20:29 UTC, augustofg commented on hdl/top/afc_v3/vivado/full/afc_full.vhd
> +      g_BENCH_MODE                             => false,
Done

2024-05-07 12:53 UTC, guilhermerc approved these changes

2024-05-07 12:58 UTC, merged